sudo: required
services:
  - docker
before_install:
  docker build -t basu2110/docker-react -f Dockerfile.dev .
scripts:
  gem install rake
  docker run basu2110/docker-react nmp run test -- -- coverage